# Generated by Django 2.2.3 on 2019-07-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('formatted_url', models.CharField(max_length=255)),
                ('html_snippet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=15)),
                ('search_phrase', models.CharField(max_length=255)),
                ('total_results', models.BigIntegerField()),
                ('page_number', models.PositiveSmallIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('most_common_words', models.ManyToManyField(to='scraper.Word')),
                ('result_items', models.ManyToManyField(to='scraper.ResultItem')),
            ],
            options={
                'verbose_name_plural': 'queries',
            },
        ),
    ]
